# Smart OCR Learning System - Docker Compose Configuration
# Complete development and production setup

version: '3.8'

services:
  smart-ocr-app:
    build:
      context: .
      dockerfile: Dockerfile.smart-ocr
    container_name: smart-ocr-learning-system
    ports:
      - "10003:10000"
    environment:
      - NODE_ENV=production
      - PORT=10000
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      - MISTRAL_ENDPOINT=https://api.mistral.ai/v1
    volumes:
      - ./smart-ocr-data:/app/smart-ocr-data
      - ./temp_smart_ocr:/app/temp_smart_ocr
      - ./temp_annotations:/app/temp_annotations
      - ./test-results:/app/test-results
    networks:
      - smart-ocr-network
    restart: unless-stopped
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10000/api/smart-ocr-test"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: smart-ocr-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - smart-ocr-network
    restart: unless-stopped
    command: redis-server --appendonly yes

  nginx:
    image: nginx:alpine
    container_name: smart-ocr-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    networks:
      - smart-ocr-network
    depends_on:
      - smart-ocr-app
    restart: unless-stopped

volumes:
  redis_data:

networks:
  smart-ocr-network:
    driver: bridge