version: '3.8'

services:
  unstructured:
    build:
      context: .
      dockerfile: Dockerfile.unstructured
    volumes:
      - ./pdfs:/app/pdfs
      - ./results:/app/results
    environment:
      - PYTHONUNBUFFERED=1
