{
  "services": [
    {
      "type": "web",
      "name": "pdf-fzzi",
      "env": "node",
      "buildCommand": "npm run build:render",
      "startCommand": "npm run start:render",
      "envVars": [
        {
          "key": "NODE_ENV",
          "value": "production"
        },
        {
          "key": "PORT",
          "value": "10002"
        }
      ]
    }
  ]
}