name: Auto-Deploy to Render

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm test
    
    - name: Run accuracy validation
      run: node test-ultimate-precision.js
      continue-on-error: true
  
  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Trigger Render Deployment
      run: |
        curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}" \
        -H "Content-Type: application/json" \
        -d '{"ref": "${{ github.ref }}"}'
    
    - name: Wait for deployment
      run: sleep 60
    
    - name: Test deployment
      run: |
        curl -f https://pdf-fzzi.onrender.com/ || exit 1
        echo "✅ Deployment successful!"